name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: go fmt check
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: ./
        gofmt-flags: -l -d

    - name: Build
      run: go build -o smfgo cmd/smfgo.go
